/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_retroarch_browser_retroactivity_RetroActivityFuture */

#ifndef _Included_com_retroarch_browser_retroactivity_RetroActivityFuture
#define _Included_com_retroarch_browser_retroactivity_RetroActivityFuture
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_retroarch_browser_retroactivity_RetroActivityFuture
 * Method:    eventCommand
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_retroarch_browser_retroactivity_RetroActivityFuture_eventCommand
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
